# Generated by Django 5.1.7 on 2025-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
